### ISSUE TITLE
Why the model cannot predict less than 14 year of age using Single Image Predictions?

### ISSUE THREAD

**Issue by QaisarRajput** [Raschka-research-group/coral-cnn#17]
Its not an issue, more of a query. I see that in the **Labels and train/test splits** section it is mentioned that 
> UTKFace: labels 0-39 correspond to ages 21-60

But as we know UTKFace data has samples from age (0 to 116) [UTKFACE](https://susanqq.github.io/UTKFace/). 

Are these models not trained on the full data-sets because of training resource needed or is there another reason?

**Comment by rasbt** [comment]
Yeah, I trimmed the dataset because some of the classes had a very low number of examples per age class. E.g., only 1-3 pictures per age class (but I don't remember the exact number, just that I trimmed it because the number of examples was very low).
