### ISSUE TITLE
Questions on (rank-monotonic) and (num_classes - 1)

### ISSUE THREAD

**Issue by Shaunlipy** [Raschka-research-group/coral-cnn#20]
Hi, Thank you for your code implementation. I have three questions would like to ask:

1. in the paper, it says "require {fk} reflect the ordinal information and are rank-monotonic". I am wondering how the rank monotonic is ensured?

2. for the "levels" variable from your code, also the paper, why choose (num_classes - 1) instead of num_classes?

Thanks

**Comment by rasbt** [comment]
Hi Shaun,

> in the paper, it says "require {fk} reflect the ordinal information and are rank-monotonic". I am wondering how the rank monotonic is ensured?

the rank monotonicity is guaranteed. The proof is provided in Theorem 1. (While not necessary, I also computed the violations of rank monotonicity, which in case of CORAL was 0, as expected. This is summarized in Table 2.)

> for the "levels" variable from your code, also the paper, why choose (num_classes - 1) instead of num_classes?

Suppose you have 3 classes, 0, 1, 2. Then, if you know whether y > 2 , by knowing y > 0  and  y > 1. Hence, the last one is redundant. E.g., if you know y>0 is True and y>1 is true, then you know y=2. Or if y > 1 is not true, you know y=2 is false

Hope that helps!
