### ISSUE TITLE
Model predicting a constant value for all images

### ISSUE THREAD

**Issue by Shubhammawa** [Raschka-research-group/coral-cnn#23]
Hello sir,
Firstly I would like to thank you for sharing this amazing repository.
I am using the VGG-16 coral.py on the UTKFace Dataset. After training the model I observed that the MAE was nearly 8.5 - 9 and was never changing irrespective of any changes in hyperparameters.
I printed the predicted_levels and actual targets and I found out that the model is predicting the same value for all images. After a few epochs the cost function almost becomes constant and the value of predicted_label is coming near 9 to 11 depending on how long the model has been trained.
I trained the model on a separate dataset: All Ages Faces Dataset and got the same issue there also.

I printed the following quantities for a few examples.
![image](https://user-images.githubusercontent.com/30144662/81222365-cef8cb80-9001-11ea-95c6-02764919798f.png)

I also printed the predicted_labels for one batch (batch_size = 64).
![image](https://user-images.githubusercontent.com/30144662/81225871-92c86980-9007-11ea-867b-5df1362a1a32.png)

I haven't changed anything in the code except adding the print statements for the above images. I am not able to figure out why this is happening. I would appreciate any insight as to why this might be happening.
Thanks!

**Comment by rasbt** [comment]
Hm, not sure to be honest. I remember that VGG16 was the worst network (worse than ResNet34 and Inceptionv3) but I haven't seen this issue when I was training it. Sorry that I can't help more here.

**Comment by Shubhammawa** [comment]
Hi, sorry for the late reply.
So basically when I was trying to train the VGG16 part of the model from scratch using UTK dataset or my own custom dataset, the model was not learning anything and just predicting nearly the average of all the outputs.
Then I used pretrained VGG16 models (pretrained on ImageNet or VGGFace datasets), added the last few necessary layers for the K-1 binary classifiers and then fine-tuned the model on the UTK dataset and my own custom dataset and got good results. I achieved an MAE of nearly 1.5 using this approach.

**Comment by fefei69** [comment]
@Shubhammawa  Would you mind sharing your work(code)? I mean the fine-tuning custom dataset part. I also would like to fine tune pre-trained cacd model using my own custom data but keep getting bad result(model predicting few constant values) #39 . I'm not sure what the problem is. Thanks in advance!
