### ISSUE TITLE
A question about level design

### ISSUE THREAD

**Issue by MakeCent** [Raschka-research-group/coral-cnn#27]
A question:
Line 165 In model-code/resnet34/afad-coral.py
`levels = [1]*label + [0]*(NUM_CLASSES - 1 - label)`
While in read me it says: "AFAD: labels 0-25 correspond to ages 15-40", which means age 15 will be label as 0, right? I check the afad_train.csv and do found some 0 labels. If age 15 is labeled as 0, then this code line creates level for age 15 with all 0 vectors. I am not very familiar with age estimation so don't know if all of you use such coding method, but if let me encode this, I will make age 15 get a 1 at least.

**Comment by rasbt** [comment]
> labels 0-25 correspond to ages 15-40", which means age 15 will be label as 0, right? 

Yes, this is correct. 

>  I check the afad_train.csv and do found some 0 labels.

That's good. Thanks for double-checking.

> If age 15 is labeled as 0, then this code line creates level for age 15 with all 0 vectors. 

Yes, your understanding is correct. 

> If age 15 is labeled as 0, then this code line creates level for age 15 with all 0 vectors. 

Yes, that's correct. The vector would be 
    
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

It can be interpreted as 

  * p(y > 15) = 0 (False)
  * p(y > 16) = 0 (False)
  * ...

I hope it clarifies this. Let me know if there is something else that is unclear.
