### ISSUE TITLE
why to use separate linear_1_bias 

### ISSUE THREAD

**Issue by darrylbobo** [Raschka-research-group/coral-cnn#3]
Hi, I did not quite understand why to use separate bias layer.

For example:

in code: 
        self.fc = nn.Linear(4096, 1, bias=False)
        self.linear_1_bias = nn.Parameter(torch.zeros(num_classes-1).float())
        
except zero initialization,  what is the difference from directly using: 
        self.fc = nn.Linear(4096, 1, bias=True) 

Thanks!

**Comment by rasbt** [comment]
If you would use 

    self.fc = nn.Linear(4096, 1, bias=True)

then you would only have a single bias value instead of "num_classes-1" bias values. Hope that clarifies!
