### ISSUE TITLE
how I use processed datasets about CACD

### ISSUE THREAD

**Issue by annoyc** [Raschka-research-group/coral-cnn#34]
like the question, I run preprocess-cacd.py file and save the processed picture to CACD2000-centered. and then I change the file path to CACD2000-centered, but when I run the cacd-coral.py ,there was an error saying that it can not find a picture with a name.

**Comment by rasbt** [comment]
You may have to update the path in the `cacd-....py ` scripts to match the path where the jpg files are located. I.e., this particular line:
![Screen Shot 2021-05-23 at 10 03 46 AM](https://user-images.githubusercontent.com/5618407/119265937-56ce5b00-bbae-11eb-86a9-ec2b2a7e267c.png)

**Comment by annoyc** [comment]
I have changed the path to  /CARD2000-center/, but it still not work,and I checked the number of all processed pictures, finding that it's a thousand fewer than unprocessed pictures.I thought the reason is that the csv file can't find the pictures preprocessed failed like the closed issue 2 said..

**Comment by rasbt** [comment]
Hm not sure what's going on. For convenience, I uploaded .tar.gz archive of the center-cropped CACD images used in the paper you can use: https://drive.google.com/file/d/198xcS0B32KBVYB9oL_W5m-7fxattDZpV/view?usp=sharing
