### ISSUE TITLE
curious about the feature 

### ISSUE THREAD

**Issue by annoyc** [Raschka-research-group/coral-cnn#35]
if I change the num_classes to double counts, like num_classes=10, and I change it to num_classes= 20. while training, the probas with a sample in the end would become like this [0.9617, 0.9617, 0.9601, 0.9601, 0.9568, 0.9568, 0.9448, 0.9448, 0.9117, 0.9117, 0.8685, 0.8685, 0.8398, 0.8398, 0.8279, 0.8279, 0.8223, 0.8223]. why it is the same value along, I thought it would be 18 different value each other,,,I want to know what decide this and how to become what i expect...

**Comment by rasbt** [comment]
When I understand correctly, you have a fixed dataset with 10 classes but then set the number of classes in CORAL to 20? If you have class labels 0, 2, 4, 6, ... then this is probably what I would expect in the results.

Say the model learns to predict
- p(y > 0) = 0.9617
- p(y > 2) = 0.9601

and it has never seen data for p(y > 1). In this case, it makes sense that the value is
- p(y > 1) = 0.9617

What value would you have expected? A value  between 0.9617 and 0.9601?

**Comment by annoyc** [comment]
thanks for reply so quickly, yes, that's exactly what  I thought.. i just dont know why its the same as p(y>0) = p(y>1)...
