### ISSUE TITLE
Ordinal Regression Code

### ISSUE THREAD

**Issue by Lucas0978** [Raschka-research-group/coral-cnn#4]
Hi!
Niu et al. propose ordinal regression with CNN.
Their loss function has w_t_i, that indicates the weight of the i-th image for the t-th
task.
This parameter from absolute cost matrix (paper formula 2).
Your loss function without this parameter in code. (e.g. afad-ordinal.py)
Can you tall me why?

**Comment by rasbt** [comment]
Yes, they included that weight in the generalized formulation but they didn't explicitly use weights. I.e., just below Eq. 2, they say that they set all weights equal to 1, which is the same as using no weighting. 

<img width="560" alt="Screen Shot 2019-07-07 at 6 08 15 PM" src="https://user-images.githubusercontent.com/5618407/60771046-41e39e00-a0e2-11e9-86f5-307f20b260e9.png">

**Comment by Lucas0978** [comment]
Thanks for your reply.

**Comment by rasbt** [comment]
You are welcome! Please let me know if you have any other questions
