### ISSUE TITLE
The download link for the training model in the paper have expired 

### ISSUE THREAD

**Issue by XCJ-LateFall** [Raschka-research-group/coral-cnn#42]
The download link for the training model in the paper have expired (https://drive.google.com/drive/folders/168ijUQyvGLhHoQUQMlFS2fVt2p5ZV2bD?usp=sharing). Where can I get the training model? Thank you very much.

**Comment by rasbt** [comment]
Thanks for your interest in this. Unfortunately, I don’t have access to the university’s Google Drive account anymore. When I moved to a startup company a few years ago, I think it got all deactivated.

The code for recreating those should be all in this directory though: https://github.com/Raschka-research-group/coral-cnn/tree/master/model-code. It takes approximately ~10h on an older 2018 GPU.
