### ISSUE TITLE
test on single image

### ISSUE THREAD

**Issue by melih1996** [Raschka-research-group/coral-cnn#6]
How to test the pretrained models on the single image?

**Comment by rasbt** [comment]
You mean the models I linked via #1? Just looking at the code, I saved them via

    torch.save(model.to(torch.device('cpu')), os.path.join(PATH, 'model.pt'))

So, 

1) you would have to install PyTorch 1.0

2) use the torch.load utility to load the file: https://pytorch.org/docs/stable/torch.html?highlight=torch%20load#torch.load

3) provide the image as torch input tensor with dimension [1, C, H, W] to the model.


I can train & save one of the  CORAL models using torch's `state_dict` approach, which will make them easier to load -- just let me know which dataset and random seed you'd prefer.

**Comment by melih1996** [comment]
I loaded the model afad-xe_seed2 like this:
torch.load('model.pt', map_location=DEVICE)

However, when I give the image as torch input tensor all the probas and logits become the same.
Here is the code that I have used
`import os
import time
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import argparse
import sys

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

from torchvision import transforms
from PIL import Image

torch.backends.cudnn.deterministic = True

# Hyperparameters
learning_rate = 0.0005
num_epochs = 200

# Architecture
NUM_CLASSES = 26
BATCH_SIZE = 256
GRAYSCALE = False

image=Image.open('melih.jpg')
custom_transform = transforms.Compose([transforms.Resize((128, 128)),
	transforms.CenterCrop((120, 120)),
	transforms.ToTensor()])
image=custom_transform(image)
DEVICE = torch.device("cpu")
image=image.to(DEVICE)

def conv3x3(in_planes, out_planes, stride=1):
    """3x3 convolution with padding"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride,
                     padding=1, bias=False)


class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(BasicBlock, self).__init__()
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = nn.BatchNorm2d(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = nn.BatchNorm2d(planes)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out


class ResNet(nn.Module):

    def __init__(self, block, layers, num_classes, grayscale):
        self.num_classes = num_classes
        self.inplanes = 64
        if grayscale:
            in_dim = 1
        else:
            in_dim = 3
        super(ResNet, self).__init__()
        self.conv1 = nn.Conv2d(in_dim, 64, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)
        self.avgpool = nn.AvgPool2d(7, stride=1, padding=2)
        self.fc = nn.Linear(2048 * block.expansion, 1, bias=False)
        self.linear_1_bias = nn.Parameter(torch.zeros(self.num_classes-1).float())

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, (2. / n)**.5)
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()

    def _make_layer(self, block, planes, blocks, stride=1):
        downsample = None
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.inplanes, planes * block.expansion,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for i in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        logits = self.fc(x)
        logits = logits + self.linear_1_bias
        probas = torch.sigmoid(logits)
        return logits, probas


def resnet34(num_classes, grayscale):
    """Constructs a ResNet-34 model."""
    model = ResNet(block=BasicBlock,
                   layers=[3, 4, 6, 3],
                   num_classes=num_classes,
                   grayscale=grayscale)
    return model

model = resnet34(NUM_CLASSES, GRAYSCALE)

model.to(DEVICE)

torch.load('model.pt', map_location=DEVICE)

image=image.unsqueeze(0)

logits, probas = model(image)


predict_levels = probas > 0.5

print(probas)

`

**Comment by melih1996** [comment]
When I run the code above, all the probas and logits are the same in each other. When I run again results change but probas and logits are become same again each other.

**Comment by melih1996** [comment]
By the way, what does xe mean in afad-xe_seed2?

**Comment by melih1996** [comment]
In addition, what is the difference between the scipts in the Resnet34 file? Are they the same?

**Comment by rasbt** [comment]
Huh, that's weird. Maybe those models I shared did not converged -- like a i mentioned in this other thread, those were not the final ones from the paper.

In any case, I just retrained 3 AFAD models and saved their `state_dict` so you can use them for "inference." 

Cross entropy classifier:

```bash
$ python afad-ce.py -i 18_years__948-0.jpg
```
```python
Class probabilities: tensor([[1.6263e-10, 5.2140e-10, 9.1224e-08, 9.9543e-01, 3.4778e-03, 1.0931e-03,
         1.0801e-06, 3.5040e-08, 1.7698e-07, 3.8712e-08, 7.7839e-12, 1.8088e-10,
         3.4035e-10, 7.5255e-12, 2.0031e-07, 6.6560e-10, 2.1507e-08, 8.9966e-08,
         1.5407e-08, 2.9739e-10, 1.3167e-12, 1.1326e-13, 3.1762e-13, 4.5134e-13,
         2.6177e-12, 2.7264e-12]])
Predicted class label: 3
Predicted age: 18
```

Niu et al's ordinal net:

```bash
$ python afad-ordinal.py -i 18_years__948-0.jpg
```
```python
Class probabilities: tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00, 2.3767e-02, 2.6130e-03, 6.1505e-05,
         4.7815e-06, 9.9883e-06, 2.6770e-08, 7.8000e-10, 8.3960e-12, 1.2439e-13,
         2.6953e-14, 7.5147e-16, 1.3262e-15, 6.9351e-16, 1.0384e-16, 1.1663e-17,
         2.9448e-18, 1.6043e-18, 2.7886e-17, 2.6531e-19, 9.3889e-19, 2.0841e-18,
         2.3151e-20]])
Predicted class label: 3
Predicted age: 18
```

and CORAL:

```bash
$ python afad-coral.py -i 18_years__948-0.jpg
```
```python
Class probabilities: tensor([[9.9747e-01, 9.4775e-01, 7.6224e-01, 2.4089e-01, 1.5139e-02, 1.2835e-03,
         1.5240e-04, 1.6612e-05, 3.0240e-06, 3.8695e-07, 5.7579e-08, 1.2740e-08,
         3.0237e-09, 8.2428e-10, 2.3996e-10, 6.3126e-11, 1.7161e-11, 5.0233e-12,
         1.4823e-12, 3.9178e-13, 8.4223e-14, 1.5927e-14, 2.5448e-15, 2.8078e-16,
         7.6178e-18]])
Predicted class label: 3
Predicted age: 18
```

The code is available from here: 
https://drive.google.com/drive/folders/1Q9vr5Q0BueHD0Kal2pEmA-NWIbYZnJAL?usp=sharing

You can download the whole folder, then `cd` into the `single-image-prediction` subdirectory and make the predictions as shown above

![Screen Shot 2019-09-03 at 10 01 22 PM](https://user-images.githubusercontent.com/5618407/64222638-7b444a00-ce96-11e9-8f74-854c7bd01a54.png)

**Comment by rasbt** [comment]
PS: Let me leave this issue open to remind me to add these examples to the README file

**Comment by melih1996** [comment]
Thanks a lot Sir now it works very well. Do you have single image prediction files and pretrained models for other datasets as well?

**Comment by melih1996** [comment]
When I use morph2 model it gives me this error although the model that you use for both are the same.
SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.AvgPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "afad-coral.py", line 182, in <module>
    model.load_state_dict(torch.load('/home/melih/Desktop/coral-cnn/single-image-prediction-20190904T054508Z-001/single-image-prediction/model1.pt', map_location=DEVICE))
  File "/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/nn/modules/module.py", line 818, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/melih/anaconda3/envs/coral/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'copy'

**Comment by melih1996** [comment]
Is there any difference between the scripts that you wrote for different data-sets other than the number of classes? If so, can I use all the models for all the data-sets by only changing the number of classes?

**Comment by rasbt** [comment]
the code should be exactly the same except for the last layer, which will be different due to the different number of classes. Let me just retrain the networks and save the state dict since I already have all the code in place (as you can see from the scripts here, I just need to uncomment the one line at the end of the scripts to save the models -- didn't do that initially because of storage concerns)

**Comment by melih1996** [comment]
Thanks Sir, I am waiting for your networks impatiently.

**Comment by tumbleintoyourheart** [comment]
Hi rasbt,

First of all thanks for sharing this great repo,

I have some questions. Hopefully, it will not bother you

In `SINGLE-IMAGE-PREDICTION/afad_coral.py'

1. can you explain what does `logits` , `probas`, `predicted_levels` mean?
2. why `predicted_label` = sum(predict_levels)

**Comment by rasbt** [comment]
@tumbleintoyourheart happy to answer, but could you please open a new issue for these questions so that we can keep this one one track regarding the fitted models

**Comment by rasbt** [comment]
@melih1996 Just uploaded the other models as well. They are available via the same link. You can find the subfolder for each script inside the `single-image-prediction` folder:

![Screen Shot 2019-09-04 at 10 44 11 PM](https://user-images.githubusercontent.com/5618407/64310430-a5187200-cf65-11e9-8508-e3064379a027.png)

**Comment by rasbt** [comment]
I added a quick example page via https://github.com/Raschka-research-group/coral-cnn/tree/master/single-image-prediction 

So I guess this issue is resolved. Let me know in case there are any difficulties with that.
